---
- name: create instance
  hosts: all
  remote_user: root
  vars:
#vars auth openstack
    ANSIBLE_PYTHON_INTERPRETER: "/usr/bin/python3.6"
    OS_USERNAME: "admin"
    OS_PASSWORD: "devstack"
    OS_REGION_NAME: "RegionOne"
    OS_AUTH_URL: "http://172.25.52.123/identity"
    OS_USER_DOMAIN_NAME: "Default"
    OS_PROJECT_DOMAIN_NAME: "Default"
    PS1: '[\u@\h \W(keystone_admin)]\$'
    OS_DNS_NAMESERVER1: "8.8.8.8"
    OS_PROJECT_NAME: "admin"
    OS_PROJECT: "ansibletest-project1"

#vars instance
    NAME_INSTANCE: "ansible_instance"
    NAME_IMAGE: "cirros-0.5.1-x86_64-disk"
    NAME_INT_NETWORK: "int_network"
    SECURITY_GROUP: "groupe1"
    KEY_NAME: ansible_key
    NAME_FLAVOR: "cirros256"
  tasks:

    - name: create a new instance
      os_server:
       state: present
       auth:
         auth_url: "{{ OS_AUTH_URL }}"
         username: "{{ OS_USERNAME }}"
         password: "{{ OS_PASSWORD }}"
         project_name: "{{ OS_PROJECT }}"
         os_user_domain_name: "{{ OS_USER_DOMAIN_NAME }}"
         os_project_domain_name: "{{ OS_PROJECT_DOMAIN_NAME }}"
       name: "{{ NAME_INSTANCE }}"
       image: "{{ NAME_IMAGE }}"
       key_name: "{{ KEY_NAME }}"
       flavor: "{{ NAME_FLAVOR }}"
       network: "{{ NAME_INT_NETWORK }}"
       security_groups: "{{ SECURITY_GROUP }}"
       auto_ip: yes
       region_name: RegionOne


