---
- name: create project 
  hosts: localhost
  
  tasks:
    - debug: var=ansible_host
    - name: Create a project
      os_project:
        state: present
        region_name: RegionOne
        domain_id: default
        name: awx
    - name: Attach admin to project
      os_user_role:
        state: present
        user: admin
        role: admin
        project: awx
...
