---
- hosts: all
  tasks:
    - openstack.cloud.project_info:
        cloud: devstack
        name: demoproject1
        domain: Default
      register: result
    - debug:
       msg: "{{ result.openstack_projects }}"
