- name: create project
  hosts: client
  tasks:
    - name: create project
      os_project:
        state: present
      name: ansible_testh
    - name: attach admin to user
      os_user_role:
        state: present
        user: admin
        role: admin
        project: ansible_testh
...
